class Code {
  static List<String> codeList = [
    "D001", "D002", "D003", "D004", "D005", "D006", "D007", "D008", "D009", "D010", "D011",
    "D012", "D013", "D014", "D015", "D016", "D017", "D018", "D019", "D020", "D021",
    "D022", "D023", "D024", "D025", "D026", "D027", "D028", "D029", "D030", "D031",
    "D032", "D033", "D034", "D035", "D036", "D037", "D038", "D039", "D040", "D041",
    "D042", "D043", "D044", "D045", "D046", "D047", "D048", "D049", "D050", "D051",
    "D052", "D053", "D054", "D055", "D056", "D057", "D058", "D059", "D060", "D061",
    "D062", "D063", "D064", "D065", "D066", "D067", "D068", "D069", "D070", "D071",
    "D072", "D073", "D074", "D075", "D076", "D077", "D078", "D079", "D080", "D081",
    "D082", "D083", "D084", "D085", "D086", "D087", "D088", "D089", "D090", "D091",
    "D092", "D093", "D094", "D095", "D096", "D097", "D098", "D099", "D100", "D101",
    "D102", "D103", "D104", "D105", "D106", "D107", "D108", "D109", "D110", "D111",
    "D112", "D113", "D114", "D115", "D116", "D117", "D118", "D119", "D120", "D121",
    "D122", "D123", "D124", "D125", "D126", "D127", "D128", "D129", "D130", "D131",
    "D132", "D133", "D134", "D135", "D136", "D137", "D138", "D139", "D140", "D141",
    "D142", "D143", "D144", "D145", "D146", "D147",
  ];
}

 class Fine {

    static List<double> fineAmount = [
            15000, 30000, 5000, 30000, 25000, 11000, 175000, 5000, 5000, 5000,
            5000, 8000, 9000, 5000, 10000, 12000, 12000, 2000, 8000, 10000, 5000,
            3000, 5000, 10000, 9000, 10000, 5000, 10000, 10000, 2000, 20000, 12000,
            30000, 12000, 20000, 30000, 6000, 10000, 15000, 10000, 100000, 25000,
            5000, 10000, 6000, 7000, 6000, 6000, 6000, 10000, 10000, 10000, 2500,
            2500, 2500, 2500, 5000, 25000, 5000, 5000, 5000, 5000, 5000, 12000,
            5000, 5000, 2000, 10000, 12000, 10000, 5000, 10000, 25000, 10000,
            10000, 3000, 5000, 5000, 5000, 5000, 5000, 8000, 20000, 5000, 5000,
            5000, 5000, 15000, 5000, 5000, 175000, 5000, 5000, 5000, 50000, 10000,
            50000, 10000, 10000, 30000, 15000, 10000, 20000, 30000, 50000, 50000,
            50000, 50000, 500000, 10000, 10000, 10000, 10000, 10000, 40000, 10000,
            5000, 10000, 30000, 4000, 40000, 20000, 5000, 50000, 5000, 10000, 5000,
            10000, 20000, 25000, 20000, 5000, 10000, 10000, 10000, 30000, 30000,
            10000, 30000, 20000, 10000, 5000, 50000, 10000, 5000, 10000, 10000
    ];
}

 class offence {

     List<String> offenceDescription = [
            "Aid And Abet No Driver’s Licence or Permit",
            "Aid And Abet Operating Motor Vehicle Contrary To The Terms Of Insurance Coverage While Acting As A Driving Instructor",
            "Body Protruding",
            "Breach of special permit",
            "Careless Driving Causing Collision",
            "Careless Driving Where No Collision Occurs",
            "Carrying dangerous goods without the transport emergency cards and manifest  Or Not Producing Emergency Cards And Manifests Upon Being Requested  By A Constable Or Other Authorized Person",
            "Carrying passenger on motor cycle on any part other than the sidecar",
            "Carrying Person Otherwise Than By Sitting Astride On Motor Cycle",
            "Causing Motor Cycle To Be Driven On One Wheel Only",
            "Child Without Child Restraint System In Motor Vehicle",
            "Crossing From A Minor Road To Major Road So As To Obstruct Traffic",
            "Crossing Road So As To Obstruct Traffic",
            "Direction indicator contrary to Regulations",
            "Disobeying Traffic Light Or Stop Sign",
            "Drawing More Than Prescribed Number of Trailers",
            "Driver Accompanying Learner Driver Having Excess Alcohol",
            "Driver Failing to Cause Passenger To Wear Seatbelt",
            "Driver Not Ensuring Pillion Wears Helmet",
            "Driver Overtaking Without A Clear View",
            "Driving a non-emergency  vehicle over a Jamaica Fire Brigade hose laid on the road for the use at a fire without consent of a Constable or other person controlling traffic or Superintendent or other officer of the JFB",
            "Driving Backwards Unnecessarily",
            "Driving closer than 50 meters behind an emergency vehicle or driving or stopping within 100 meters of where an emergency vehicle stopped",
            "Driving Defective Motor Vehicle",
            "Driving From A Place That Is Not A Road Onto A Road So As To Obstruct Traffic",
            "Driving Instructor Holding Or Using Electronic Communication Device While Providing Instructions",
            "Driving Or Attempting To Drive Motor Vehicle Across Funeral Procession",
            "Driving/Operating Motor Vehicle While Using Electronic Communication Device",
            "Driving/Operating Motor Vehicle While Using Specified Electronic Visual Device Within Driver’s Line Of Sight",
            "Driving/Riding in a Motor Vehicle Without Seatbelt On",
            "Exceeding Speed Limit In Construction Zone; 33-49 Kilometers Per Hour",
            "Exceeding Speed Limit In Construction Zone;16-32 Kilometers Per Hour",
            "Exceeding Speed Limit In Construction Zone;50 Or More Kilometers Per Hour",
            "Exceeding Speed Limit In School Safety Zone; 16 To 32 Kilometers Per Hour",
            "Exceeding Speed Limit In School Safety Zone; 33 To 49 Kilometers Per Hour",
            "Exceeding Speed Limit In School Safety Zone; 50 or More Kilometres Per Hour",
            "Exceeding Speed Limit; 16-32 Kilometers Per Hour",
            "Exceeding Speed Limit; 33-49 Kilometers Per Hour",
            "Exceeding Speed Limit; 50 Or More Kilometers Per Hour",
            "Excess Noise",
            "Excess Weight 1001-5000 Kilogram",
            "Excess Weight 500-1000 Kilogram",
            "Failing To Allow Vehicle To Be Overtaken",
            "Failing To Bring Motor Vehicle To A Full Stop Where No Traffic Sign is Posted Or Constable is Assigned",
            "Failing To Comply With Other Traffic  Signs",
            "Failing To Comply With Requirement To Off-Load Vehicle When Vehicle Is Found To Be Above Prescribed Laden Weight In A Manner So As Not To Obstruct Traffic",
            "Failing To Comply With Terms And Conditions Of Driver’s Licence",
            "Failing To Comply With Terms And Conditions Of Learner’s Permit",
            "Failing To Comply With Terms Of Condition Of Driver’s Licence During First Twelve (12) Months",
            "Failing To Comply With Traffic Sign In Construction Zone",
            "Failing To Comply With Traffic Sign In School Zone",
            "Failing To Comply With Traffic Signs Or Direction Of Constable Before Turning Into or Crossing a Major Road Where Roadway Is Not Controlled By Traffic Light",
            "Failing To Fit Mechanical or illuminated Device (No indicator)",
            "Failing To Give Appropriate Signal When Approaching A Constable At Road Junction To Indicate Which Direction Driver Will Go",
            "Failing To Give Signal To Stop",
            "Failing To Give Turning Signal (Failing to Indicate)",
            "Failing to have certificate showing exemption from wearing seatbelt",
            "Failing to inform police of route where radioactive or infectious goods will be transported at least five days before transportation",
            "Failing To Keep Left Or Nearside Of The Road When Being Overtaken",
            "Failing To Keep Right Or Offside Of Other Traffic Whilst Overtaking",
            "Failing to label protective device",
            "Failing To Obey Constable Command",
            "Failing To Observe Silent Zone",
            "Failing To Observe Stop For Crossing When Required By A School Crossing Warden",
            "Failing To Place Motor Vehicle Not In Motion As Indicated By Constable Or By Notice Issued By The Authority",
            "Failing To Place Motor Vehicle When Not In Motion In A Safe Position",
            "Failing To Produce Driver’s Licence/Permit At Constable’s Request",
            "Failing to prominently display license or certified copy at driving school",
            "Failing To Remain Stationery When Stopped By School Crossing Warden",
            "Failing To Stop Or Observe Provisions Of A Pedestrian Crossing",
            "Failing to use emergency warning sign",
            "Failing To Yield Right Of Way at Pedestrian Crossing",
            "Failing to yield right of way to emergency vehicles",
            "Fitting or using lamp fitted in contravention of the Regulations",
            "Fraudulent Use Of Registration Plate or Decal",
            "Leaving Motor Vehicle Unattended Without Stopping Engine",
            "Leaving/Abandoning Motor Vehicle On Road Causing Obstruction",
            "Licence Disc Not Affixed",
            "More Person On Motor Cycle",
            "No Brake Light",
            "No Headlamp",
            "No Helmet",
            "No Motor Vehicle Insurance",
            "No Park Light",
            "No Rear Registration Plate Light",
            "No Reflectors",
            "No Seat Belt In Motor Vehicle",
            "No Valid Certificate Of Fitness",
            "No Warning Devices",
            "Not Parked With Near Side Closed To The Left As Possible When Not In Motion",
            "Not producing transport emergency cards and manifests upon being requested to by a Constable or other authorized person",
            "Obscured Licence Disc",
            "Obscured Registration Plate",
            "Obstructing Traffic",
            "Operating a driving school without being licensed",
            "Operating a motor cycle on a road where any goods carried theron exceeds prescribed projection",
            "Operating a motor vehicle that requires a special permit without obtaining such special permit",
            "Operating Motor Vehicle Contrary To Terms and Conditions Of Licence",
            "Operating Motor Vehicle Contrary To Terms Of Licence Issued To Dealer.",
            "Operating motor vehicle contrary to the terms of Insurance coverage while acting as a driving instructor",
            "Operating motor vehicle fitted with lamps emitting blue light or capable of emitting blue lights",
            "Operating motor vehicle fitted with spot lamp enabling beam of light to be deflected in any direction",
            "Operating motor vehicle on a road where the overall height exceeds 4.2 metres from the ground",
            "Operating motor vehicle or trailer where the load projects more than 15 centimetres beyond either side without the use of the required warning device to indicate the extent of the projection",
            "Operating motor vehicle or trailer where the load projects more than 30 centimetres beyond the rear without the use of the required warning device to indicate the width or length of projection",
            "Operating motor vehicle specified in Regulation 259(1) if the overall length of the vehicle exceeds that specified in Regulation 32",
            "Operating motor vehicle specified in Regulation 259(1) if the overall width of the vehicle exceeds 3.5 meters",
            "Operating motor vehicle specified in Regulation 259(1) if the overall width of the vehicle exceeds that specified in Regulation 33",
            "Operating motor vehicle specified in Regulation 259(1) in time when motor vehicle cannot be clearly discerned at a distance of 150 meters",
            "Operating motor vehicle where exhaust pipe or silencer is not in good working order",
            "Operating motor vehicle where exhaust pipe or silencer is placed and maintained so that exhaust or smoke leaks into the driving cab or passenger compartment",
            "Operating motor vehicle where exhaust pipe or silencer when tested exceeds the Jamaica Motor Vehicle Exhaust Emission Standard limits",
            "Operating motor vehicle where the exhaust or smoke from the engine causes nuisance or obstruction to the vision of other road users",
            "Operating motor vehicle where the exhaust pipe or silencer is in such a position that oil or other flammable liquid or material can drip or fall onto the exhaust pipe or silencer",
            "Operating Motor Vehicle Without Driver’s Licence/Permit",
            "Overtaking Causing Obstruction",
            "Parking In Such A Position As To Obstruct Traffic",
            "Passing Or Overtaking Vehicle Stopped At Pedestrian Crossing",
            "Permitting another person to use motor vehicle not covered by insurance which includes coverage for driving instruction while acting as a driving instructor",
            "Pouring Petrol With Engine Running Or With Naked Light",
            "Providing services of a driving instructor without being certified by the Authority",
            "Refusal To Allow Vehicle To Be Weighed Or Tested",
            "Riding on the outside of a vehicle",
            "Selling, distributing or using a photographic image or video captured by an electronic enforcement device other than for the prosecution of a Part IV offence",
            "Sitting or travelling or permitting person to sit or travel with load being transported",
            "Smoking Ganja While Driving Or Attempting To Drive Or While Being In Charge Of A Vehicle On A Road",
            "Stopping or parking a non-emergency vehicle at a point within 3 metres of either side of  a fire hydrant without consent of a Constable or the Superintendent or other officer of the Jamaica Fire Brigade",
            "Stopping within 12 metres of a bus stop sign",
            "Towing motor vehicle on a toll road by means other than by a tow truck",
            "Transporting dangerous goods while carrying passengers who are unqualified",
            "Transporting dangerous goods without being certified to do so",
            "Travelling on or permitting a person to travel or drive in or on a motor vehicle or trailer while body protrudes beyond the side or rear",
            "Unlawful Use Of Siren Or Other Similar Device",
            "Unlicensed Motor Vehicle",
            "Unregistered Motor Vehicle",
            "Using a car to draw a trailer where the unladen weight equals or exceeds the weight of the drawing vehicle",
            "Using a motor tractor to draw more than two trailers at one time",
            "Using a revolving lamp in contravention of Regulation 103",
            "Using a truck to draw more than one trailer at any one time",
            "Using an articulated motor vehicle to draw a trailer",
            "Using Electronic Communication Device While Driving Or Operating A Vehicle",
            "Using motor vehicle on the road which is not licensed in accordance with the Act",
            "Using motor vehicle to damage road sign",
            "Using motor vehicle to tow a broken down or disabled vehicle in contravention of Regulation 249(1)",
            "Using motor vehicle while on a road that is not a main road to travel backwards longer than necessary for the safety or convenience of the occupants or other road users and traffic on the road",
            "Using Wireless Communication Device To View Send Or Compose An Electronic Message While Driving",
            "Wilfully Defacing Or Destroying Document"
     ];

}


 class point
{

        List<int>  points = [
   
0,
0,
0,
0,
10,
4,
0,
0,
0,
3,
4,
3,
3,
0,
6,
4,
0,
2,
2,
3,
0,
4,
0,
2,
3,
6,
2,
4,
6,
2,
6,
3,
10,
3,
6,
10,
2,
4,
6,
0,
0,
0,
2,
0,
3,
0,
2,
2,
2,
3,
2,
0,
2,
2,
2,
2,
0,
0,
3,
3,
0,
1,
2,
6,
0,
0,
0,
0,
6,
4,
0,
4,
0,
0,
0,
0,
0,
0,
3,
2,
4,
2,
0,
2,
2,
2,
2,
0,
2,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
14,
3,
0,
4,
0,
0,
0,
0,
0,
0,
0,
2,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
0,
4,
0,
0,
0,
0,
0,
0,


        ];
    }




 class section {

 List<String> sectionOfRTA = [
            "Section 20(4)",
            "Regulation 180(2)",
            "Regulation 261(4)",
            "Regulation 113(8)",
            "Section 59(1)",
            "Section 59(1)",
            "Regulation 291(3)",
            "Regulation 261(4)",
            "Section 67(2)",
            "Section 67(2)",
            "Section 73(2)",
            "Section 54(4)b",
            "Section 57(5)(d)(iii)",
            "Regulation 110(3)",
            "Section 52(2)(a)",
            "Section 68(3)",
            "Section 24(4)",
            "Section 72(4)",
            "Section 74(3)",
            "Section 57(5)(d)(i)",
            "Regulation 284(2)",
            "Section 57(5)(f)",
            "Regulation 283(2)",
            "Section 123(d)",
            "Section 57(5) (e)",
            "Section 121(4)",
            "Section 123(h)",
            "Section 121(4)",
            "Section 122(3)",
            "Section 72(4)",
            "Section (77)(3)",
            "Section 77(3)",
            "Section 77(3)",
            "Section 76(4)",
            "Section 76(4)",
            "Section 76(4)",
            "Section 55(3)",
            "Section 55(3)",
            "Section 55(3)",
            "Regulation 247(7)",
            "Section 102(1)(b)",
            "Section 102(1)(a)",
            "Section 57(5)(c)",
            "Section 54(4)(a)(ii)",
            "Section 52(2)(b)",
            "Section 104(3)",
            "Section 27(3)",
            "Section 24(4)",
            "Section 27(3)",
            "Section 77(3)",
            "Section 76(4)",
            "Section 54(4)(a)(i)",
            "Section 90(6)",
            "Section 90(6)",
            "Section 90(6)",
            "Section 90(6)",
            "Regulation 281(3)",
            "Regulation 294(2)",
            "Section 57(5)(a)",
            "Section 57(5)(b)",
            "Regulation 276(4)",
            "Section 91(2)",
            "Section 75(1)",
            "Section 81(3)(a)",
            "Section 89(4)",
            "Section 89(4)",
            "Section 20(4)",
            "Regulation 188(2)",
            "Section 81(3)(b)",
            "Section 83(3)",
            "Regulation 262(6)",
            "Section 83(3)",
            "Regulation 282(3)",
            "Regulation 85(9)",
            "Section 13(3)",
            "Section 89(4)",
            "Section 94(1)",
            "Section 13(5)",
            "Section 67(2)",
            "Section 71(2)(e)",
            "Section 71(2)(a)",
            "Section 74(3)",
            "Section 7(3)",
            "Section 71(2)(b)",
            "Section 71(2)(d)",
            "Section 71(2)(c)",
            "Section 71(2)(g)",
            "Section 7(3)",
            "Section 71(2)(f)",
            "Section 89(4)",
            "Regulation 291(3)",
            "Section 13(5)",
            "Section 13(5)",
            "Section 93(3)",
            "Regulation 183(2)",
            "Regulation 257(3)",
            "Regulation 113(7)",
            "Section 13(5)",
            "Section 13(4)",
            "Regulation 180(2)",
            "Regulation 102(4)",
            "Regulation 101(3)",
            "Regulation 255(2)",
            "Regulation 258(6)",
            "Regulation 258(6)",
            "Regulation 259(8)",
            "Regulation 259(8)",
            "Regulation 259(8)",
            "Regulation 259(8)",
            "Regulation 66(2)",
            "Regulation 66(2)",
            "Regulation 66(2)",
            "Regulation 66(2)",
            "Regulation 66(2)",
            "Section 20(4)",
            "Section 57(d)(ii)",
            "Section 89(4)",
            "Section 83(3)",
            "Regulation 180(2)",
            "Section 89(4)",
            "Regulation 168(4)",
            "Section 103(2)",
            "Section 88(2)",
            "Regulation 242(4)",
            "Regulation 261(4)",
            "Section 123",
            "Regulation 284(2)",
            "Regulation 204(2)",
            "Regulation 249(5)",
            "Regulation 286(4)",
            "Regulation 290(2)",
            "Regulation 261(4)",
            "Section 52(7)",
            "Section 7(3)",
            "Section 7(3)",
            "Regulation 250(2)",
            "Regulation 250(2)",
            "Regulation 103(7)",
            "Regulation 250(2)",
            "Regulation 249(5)",
            "Section 121(4)",
            "Section 13(5)",
            "Regulation 203(3)",
            "Regulation 249(5)",
            "Regulation 220(2)",
            "Section 121(4)",
            "Section 108(2)"
    ];
}


class OffenceClass {
  String offence;
  String code;
  double findAmount;
  int points;
  String section;
  

  OffenceClass({
    required this.offence,
    required this.code,
    required this.findAmount,
    required this.points,
    required this.section,
   
  });

  factory OffenceClass.fromJson(Map<String, dynamic> json) {
    return OffenceClass(
      offence: json['offence'],
      code: json['code'],
      findAmount: json['findAmount'].toDouble(),
      points: json['points'],
      section: json['section'],

    );
  }

  Map<String, dynamic> toJson() {
    return {
      'offence': offence,
      'code': code,
      'findAmount': findAmount,
      'points': points,
      'section': section,
   
    };
  }
}


class WordingBook {
 int  number;
 String title;
 String Offence;

 WordingBook({
   required this.number,
    required this.title,
    required this.Offence,
   

 });

}